apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-test-consumer-deployment
  namespace: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-test-consumer
  template:
    metadata:
      labels:
        app: kafka-test-consumer
    spec:
      containers:
        - name: kafka-test-consumer
          image: test-kafka-consumer
          imagePullPolicy: Never
          ports:
            - containerPort: 8081

---
apiVersion: v1
kind: Service
metadata:
  name: kafka-test-consumer-service
  namespace: kafka
spec:
  selector:
    app: kafka-test-consumer-service
  ports:
    - name: kafka-test-service-port
      protocol: TCP
      port: 8081
      targetPort: 8081
